# By RZFeeser

name: Playwright Tests

# triggered on button press, or changes to main or master branches
on:
  workflow_dispatch:                # manual trigger
  push:                             # git commit trigger
    branches: [ main, master ]
  pull_request:                     # pull request trigger
    branches: [ main, master ]

jobs:
  test:    
    timeout-minutes: 60             # if the job hangs longer than 1 hour, abort
    
    runs-on: ubuntu-latest
    steps:
    - name: checkout code from repository
      uses: actions/checkout@v4
      
    - name: setup javascript within runner
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test
    
    - name: create an artifact with playwright results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}             # do not create artifact if canceled
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
